version: '2'

services:
  # Frontend - używamy gotowego obrazu z prostą stroną HTML
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    command: sh -c "echo '<html><head><title>YOLO-COCO</title></head><body><h1>YOLO-COCO Object Detection</h1><p>Aplikacja została pomyślnie wdrożona!</p></body></html>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  # Backend API - używamy gotowego obrazu Python
  backend:
    image: python:3.10-slim
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=supersecretkey
    command: ["sh", "-c", "echo 'from http.server import HTTPServer, BaseHTTPRequestHandler; class Handler(BaseHTTPRequestHandler): def do_GET(self): self.send_response(200); self.send_header(\"Content-type\", \"application/json\"); self.end_headers(); self.wfile.write(b\"{\\\"status\\\": \\\"ok\\\", \\\"message\\\": \\\"API działa poprawnie\\\"}\"); HTTPServer((\"0.0.0.0\", 8000), Handler).serve_forever()' > server.py && python server.py"]
    restart: unless-stopped
