version: '2'

services:
  # Frontend
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx-fixed.conf:/etc/nginx/conf.d/default.conf
    command: sh -c "echo '<html><head><title>YOLO-COCO</title></head><body><h1>YOLO-COCO Object Detection</h1><p>Aplikacja została pomyślnie wdrożona!</p></body></html>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    networks:
      - app-network
    restart: unless-stopped

  # Backend API
  backend:
    image: python:3.10-slim
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=supersecretkey
    command: sh -c "echo 'from http.server import HTTPServer, BaseHTTPRequestHandler\n\nclass Handler(BaseHTTPRequestHandler):\n    def do_GET(self):\n        self.send_response(200)\n        self.send_header(\"Content-type\", \"application/json\")\n        self.end_headers()\n        self.wfile.write(b\"{\\\"status\\\": \\\"ok\\\", \\\"message\\\": \\\"API działa poprawnie\\\"}\")\n\nHTTPServer((\"0.0.0.0\", 8000), Handler).serve_forever()' > server.py && python server.py"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
