version: '2'

services:
  # Frontend
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  # Backend API
  backend:
    image: python:3.10-slim
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=supersecretkey
    command: ["sh", "-c", "echo 'Backend container is running'"]
    restart: unless-stopped
