FROM python:3.10-slim

WORKDIR /app

# Kopiowanie plików wymagań
COPY requirements.txt .

# Instalacja zależności
RUN pip install --no-cache-dir -r requirements.txt

# Kopiowanie kodu aplikacji
COPY ./app /app/app

# Ustawienie zmiennych środowiskowych
ENV PYTHONPATH=/app
ENV C_FORCE_ROOT=true

# Uruchomienie workera Celery
CMD ["celery", "-A", "app.worker.celery", "worker", "--loglevel=info"]
